/* Generated By:JavaCC: Do not edit this line. ArithmeticalGrammarConstants.java */
package expresii_aritmetice;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ArithmeticalGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int EQUAL = 12;
  /** RegularExpression Id. */
  int AT_SIGN = 13;
  /** RegularExpression Id. */
  int POUND_SIGN = 14;
  /** RegularExpression Id. */
  int DOLLAR_SIGN = 15;
  /** RegularExpression Id. */
  int PERCENT_SIGN = 16;
  /** RegularExpression Id. */
  int CARET = 17;
  /** RegularExpression Id. */
  int AMPERSAND = 18;
  /** RegularExpression Id. */
  int TILDE = 19;
  /** RegularExpression Id. */
  int LESS_THAN = 20;
  /** RegularExpression Id. */
  int GREATER_THAN = 21;
  /** RegularExpression Id. */
  int QUESTION_MARK = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int LEFT_CURLY_BARCE = 24;
  /** RegularExpression Id. */
  int RIGHT_CURLY_BRACE = 25;
  /** RegularExpression Id. */
  int DOT = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int LL = 28;
  /** RegularExpression Id. */
  int CONSTANT = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"=\"",
    "\"@\"",
    "\"#\"",
    "\"$\"",
    "\"%\"",
    "\"^\"",
    "\"&\"",
    "\"~\"",
    "\"<\"",
    "\">\"",
    "\"?\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\",\"",
    "<LL>",
    "<CONSTANT>",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
