/* Generated By:JavaCC: Do not edit this line. RelationalGrammarConstants.java */
package expresii_relationale;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RelationalGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANT = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int LESS_THAN = 9;
  /** RegularExpression Id. */
  int GREATER_THAN = 10;
  /** RegularExpression Id. */
  int LESS_THAN_EQUAL = 11;
  /** RegularExpression Id. */
  int GREATER_THAN_EQUAL = 12;
  /** RegularExpression Id. */
  int EQUAL = 13;
  /** RegularExpression Id. */
  int NOT_EQUAL = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int EQUAL2 = 18;
  /** RegularExpression Id. */
  int AT_SIGN = 19;
  /** RegularExpression Id. */
  int POUND_SIGN = 20;
  /** RegularExpression Id. */
  int DOLLAR_SIGN = 21;
  /** RegularExpression Id. */
  int PERCENT_SIGN = 22;
  /** RegularExpression Id. */
  int CARET = 23;
  /** RegularExpression Id. */
  int AMPERSAND = 24;
  /** RegularExpression Id. */
  int ASTERISK = 25;
  /** RegularExpression Id. */
  int FORWARD_SLASH = 26;
  /** RegularExpression Id. */
  int TILDE = 27;
  /** RegularExpression Id. */
  int QUESTION_MARK = 28;
  /** RegularExpression Id. */
  int COLON = 29;
  /** RegularExpression Id. */
  int LEFT_CURLY_BARCE = 30;
  /** RegularExpression Id. */
  int RIGHT_CURLY_BRACE = 31;
  /** RegularExpression Id. */
  int DOT = 32;
  /** RegularExpression Id. */
  int COMMA = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<CONSTANT>",
    "\"(\"",
    "\")\"",
    "<IDENTIFIER>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"=\"",
    "\"@\"",
    "\"#\"",
    "\"$\"",
    "\"%\"",
    "\"^\"",
    "\"&\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\",\"",
    "\";\"",
  };

}
