/* Generated By:JavaCC: Do not edit this line. LogicalGrammarConstants.java */
package expresii_logice;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LogicalGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int EQUAL = 8;
  /** RegularExpression Id. */
  int AT_SIGN = 9;
  /** RegularExpression Id. */
  int POUND_SIGN = 10;
  /** RegularExpression Id. */
  int DOLLAR_SIGN = 11;
  /** RegularExpression Id. */
  int PERCENT_SIGN = 12;
  /** RegularExpression Id. */
  int CARET = 13;
  /** RegularExpression Id. */
  int AMPERSAND = 14;
  /** RegularExpression Id. */
  int ASTERISK = 15;
  /** RegularExpression Id. */
  int FORWARD_SLASH = 16;
  /** RegularExpression Id. */
  int TILDE = 17;
  /** RegularExpression Id. */
  int LESS_THAN = 18;
  /** RegularExpression Id. */
  int GREATER_THAN = 19;
  /** RegularExpression Id. */
  int QUESTION_MARK = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int LEFT_CURLY_BARCE = 22;
  /** RegularExpression Id. */
  int RIGHT_CURLY_BRACE = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int IDENTIFIER = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"==\"",
    "\"@\"",
    "\"#\"",
    "\"$\"",
    "\"%\"",
    "\"^\"",
    "\"&\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\"<\"",
    "\">\"",
    "\"?\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\",\"",
    "<IDENTIFIER>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
  };

}
